### INDEX
GET http://localhost:8080/api/discounts?page=1&per_page=5
Accept: application/json
Authorization: Bearer my-secret-token

###

### SHOW
GET http://localhost:8080/api/discounts/1
Authorization: Bearer my-secret-token

###

### CREATE
POST http://localhost:8080/api/discounts
Authorization: Bearer my-secret-token
Content-Type: application/json

{
    "tanggal":"2026-07-20",
    "nominal":100000
}

###

### UPDATE
PUT http://localhost:8080/api/discounts/30
Authorization: Bearer my-secret-token
Content-Type: application/json

{
    "nominal":120000
}

###

### DELETE
DELETE http://localhost:8080/api/discounts/32
Authorization: Bearer my-secret-token